image: golang:latest

variables:
  REPO_NAME: github.com/taskie/jc

before_script:
  - 'mkdir -p $GOPATH/src/$(dirname $REPO_NAME)'
  - 'ln -svf $CI_PROJECT_DIR $GOPATH/src/$REPO_NAME'
  - 'cd $GOPATH/src/$REPO_NAME'

stages:
  - test
  - build

format:
  stage: test
  script:
    - 'mkdir -p bin'
    - 'curl -fsSL -C - -o bin/dep https://github.com/golang/dep/releases/download/v0.5.0/dep-linux-amd64'
    - 'chmod +x bin/dep'
    - 'bin/dep ensure -v'
    - 'go fmt $(go list ./... | grep -v /vendor/)'
    - 'go vet $(go list ./... | grep -v /vendor/)'
    - 'go test -race -cover $(go list ./... | grep -v /vendor/)'

compile:
  stage: build
  script:
    - 'cd cmd/jc'
    - 'go build'
  artifacts:
    paths:
      - cmd/jc/jc

cache:
  key: '$CI_COMMIT_REF_SLUG'
  paths:
    - bin/dep
    - vendor
